from __future__ import annotations

from datetime import datetime, timezone

from icalendar import Calendar, Event


def _to_utc(dt: datetime) -> datetime:
    """Normalize datetime to aware UTC (naive is treated as UTC)."""
    if dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _build_summary(study_time: dict) -> str:
    course_name = (study_time.get("course_name") or "").strip()
    assignment_name = (study_time.get("assignment_name") or "").strip()
    if course_name and assignment_name:
        return f"Study: {course_name} — {assignment_name}"
    if course_name:
        return f"Study: {course_name}"
    if assignment_name:
        return f"Study: {assignment_name}"
    return "Study Session"


def _build_description(study_time: dict) -> str:
    lines = ["Generated by Syllabify"]
    course_name = (study_time.get("course_name") or "").strip()
    assignment_name = (study_time.get("assignment_name") or "").strip()
    notes = (study_time.get("notes") or "").strip()

    if course_name:
        lines.append(f"Course: {course_name}")
    if assignment_name:
        lines.append(f"Assignment: {assignment_name}")
    lines.append(
        "Status: Locked by user"
        if bool(study_time.get("is_locked"))
        else "Status: Auto-scheduled"
    )
    if notes:
        lines.append(f"Notes: {notes}")
    return "\n".join(lines)


def serialize_study_times_to_ics(
    study_times: list[dict], generated_at: datetime | None = None
) -> bytes:
    """
    Build RFC5545-compatible ICS feed for StudyTimes.
    Uses stable UID format: studytime-<id>@syllabify.
    """
    generated = _to_utc(generated_at or datetime.utcnow())

    cal = Calendar()
    cal.add("prodid", "-//Syllabify//Study Plan Export//EN")
    cal.add("version", "2.0")
    cal.add("calscale", "GREGORIAN")
    cal.add("method", "PUBLISH")
    cal.add("X-WR-CALNAME", "Syllabify Study Plan")
    cal.add("X-WR-CALDESC", "Auto-generated study schedule from Syllabify")

    for st in study_times:
        start = st.get("start_time")
        end = st.get("end_time")
        if not isinstance(start, datetime) or not isinstance(end, datetime):
            continue
        if end <= start:
            continue

        event = Event()
        event.add("uid", f"studytime-{st['id']}@syllabify")
        event.add("dtstamp", generated)
        event.add("last-modified", generated)
        event.add("dtstart", _to_utc(start))
        event.add("dtend", _to_utc(end))
        event.add("summary", _build_summary(st))
        event.add("description", _build_description(st))
        event.add("status", "CONFIRMED")
        cal.add_component(event)

    return cal.to_ical()
